profile: local

reflex:
  deploy_url: http://localhost
  frontend_port: 8080

app:
  environment: local
  logging: logging.yaml

  database:
    echo: True

  authentication:
    server_url: http://localhost:8080
    session_timeout: 15 # minutes
    auth_token_refresh_delta: 12 # minutes

    oauth_providers:
      - provider: "github"
        client_id: secret:mn-oauth-github-client-id
        client_secret: secret:mn-oauth-github-client-secret
        redirect_url: http://localhost:8080/oauth/github/callback
      - provider: "azure"
        client_id: secret:mn-oauth-azure-client-id
        client_secret: secret:mn-oauth-azure-client-secret
        tenant_id: secret:mn-oauth-azure-tenant-id
        redirect_url: http://localhost:8080/oauth/azure/callback
