profile: default

reflex:
  deploy_url: http://localhost
  frontend_port: 3000
  backend_port: 3031
  workers: 1

app:
  version: 1.5.1
  name: appkit App
  logging: logging.prod.yaml
  environment: prod
  backend_timeout: 180 # seconds

  database:
    username: secret:mn-db-user
    password: secret:mn-db-password
    host: secret:mn-db-host
    port: 5432
    name: secret:mn-db-name
    encryption_key: secret:mn-db-encryption-key
    pool_size: 10 # change only when needed
    max_overflow: 20 # change only when needed
    pool_recycle: 1800 # seconds; recycle connections to prevent stale SSL
    echo: False # Set to True to enable SQL logging

  authentication:
    session_timeout: 25 # minutes
    auth_token_refresh_delta: 10 # minutes
    session_monitor_interval_seconds: 60 # seconds
    server_url: https://localhost
    server_port: 8080

    oauth_providers:
      - provider: "github"
        client_id: secret:mn-oauth-github-client-id
        client_secret: secret:mn-oauth-github-client-secret
        redirect_url: https://localhost:8080/oauth/github/callback

  assistant:
    file_upload:
      vector_store_expiration_days: 2
      max_file_size_mb: 50
      max_files_per_thread: 10
      cleanup_interval_minutes: 60

  imagegenerator:
    tmp_dir: ./uploaded_files
    cleanup_days_threshold: 60
